const { vw } = require('../utils/vw')

const media = {
  '.media': {
    position: 'relative',
    overflow: 'hidden',
    objectFit: 'cover',
    borderColor: 'var(--color-media-border)',
    '--tw-shadow-color': 'var(--color-media-shadow)',
    '--tw-shadow': 'var(--tw-shadow-colored)',
    borderStyle: 'solid',
    borderWidth: vw('var(--media-border-width)', 'sm'),
    borderRadius: vw('var(--media-border-radius)', 'sm'),
    boxShadow: `${vw('var(--media-shadow-x)', 'sm')} ${vw('var(--media-shadow-y)', 'sm')} ${vw('var(--media-shadow-blur)', 'sm')} ${vw('var(--media-shadow-spread)', 'sm')} var(--tw-shadow-color, rgba(0, 0, 0, 0.25))`,
    '@screen md': {
      borderWidth: vw('var(--media-border-width)', 'lg'),
      borderRadius: vw('var(--media-border-radius)', 'lg'),
      boxShadow: `${vw('var(--media-shadow-x)', 'lg')} ${vw('var(--media-shadow-y)', 'lg')} ${vw('var(--media-shadow-blur)', 'lg')} ${vw('var(--media-shadow-spread)', 'lg')} var(--tw-shadow-color, rgba(0, 0, 0, 0.25))`,
    },
    '> iframe, > img, > video': {
      width: '100% !important',
      height: '100% !important',
      aspectRatio: 'auto',
    },
  },
  '.media-wrapper': {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: vw('var(--media-border-radius)', 'sm'),
    '@screen md': {
      borderRadius: vw('var(--media-border-radius)', 'lg'),
    },
  },
  '.media-poster': {
    pointerEvents: 'auto',
    zIndex: 1,
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    objectPosition: 'center',
    transform: 'scale(1)',
    opacity: 1,
    transitionProperty: 'transform, opacity',
    transitionTimingFunction: 'cubic-bezier(0.215, 0.61, 0.355, 1)',
    transitionDuration: '500ms',
  },
  '.media-overlay': {
    pointerEvents: 'auto',
    zIndex: 2,
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'var(--color-media-overlay)',
    opacity: 1,
    transitionProperty: 'opacity',
    transitionTimingFunction: 'cubic-bezier(0.215, 0.61, 0.355, 1)',
    transitionDuration: '500ms',
  },
  '.media-icon': {
    pointerEvents: 'auto',
    zIndex: 3,
    position: 'absolute',
    top: '50%',
    left: '50%',
    translate: '-50% -50%',
    width: vw('var(--media-icon-holder-size)', 'sm'),
    height: vw('var(--media-icon-holder-size)', 'sm'),
    display: 'inline-grid',
    placeItems: 'center',
    borderRadius: vw('var(--media-icon-holder-border-radius)', 'sm'),
    backgroundColor: 'var(--color-media-icon-background)',
    borderWidth: vw('var(--media-icon-holder-border-width)', 'sm'),
    borderStyle: 'solid',
    borderColor: 'var(--color-media-icon-border)',
    '--tw-shadow-color': 'var(--color-media-icon-shadow)',
    '--tw-shadow': 'var(--tw-shadow-colored)',
    boxShadow: `${vw('var(--media-icon-holder-shadow-x)', 'sm')} ${vw('var(--media-icon-holder-shadow-y)', 'sm')} ${vw('var(--media-icon-holder-shadow-blur)', 'sm')} ${vw('var(--media-icon-holder-shadow-spread)', 'sm')} var(--tw-shadow-color, rgba(0, 0, 0, 0.25))`,
    color: 'var(--color-media-icon-fill)',
    transform: 'scale(1)',
    opacity: 1,
    transitionProperty: 'transform, opacity',
    transitionTimingFunction: 'cubic-bezier(0.215, 0.61, 0.355, 1)',
    transitionDuration: '300ms',
    '@screen md': {
      width: vw('var(--media-icon-holder-size)', 'lg'),
      height: vw('var(--media-icon-holder-size)', 'lg'),
      borderRadius: vw('var(--media-icon-holder-border-radius)', 'lg'),
      borderWidth: vw('var(--media-icon-holder-border-width)', 'lg'),
      boxShadow: `${vw('var(--media-icon-holder-shadow-x)', 'lg')} ${vw('var(--media-icon-holder-shadow-y)', 'lg')} ${vw('var(--media-icon-holder-shadow-blur)', 'lg')} ${vw('var(--media-icon-holder-shadow-spread)', 'lg')} var(--tw-shadow-color, rgba(0, 0, 0, 0.25))`,
    },
    '> *': {
      width: vw('var(--media-icon-size)', 'sm'),
      height: vw('var(--media-icon-size)', 'sm'),
      '@screen md': {
        width: vw('var(--media-icon-size)', 'lg'),
        height: vw('var(--media-icon-size)', 'lg'),
      },
    },
  },
  '.media-caption': {
    backgroundColor: 'var(--color-media-caption-background)',
    color: 'var(--color-media-caption-text)',
    paddingBlock: vw('var(--media-caption-padding-y)', 'sm'),
    paddingInline: vw('var(--media-caption-padding-x)', 'sm'),
    marginTop: vw('var(--media-caption-margin-top)', 'sm'),
    borderRadius: vw('var(--media-caption-border-radius)', 'sm'),
    '@screen md': {
      paddingBlock: vw('var(--media-caption-padding-y)', 'lg'),
      paddingInline: vw('var(--media-caption-padding-x)', 'lg'),
      marginTop: vw('var(--media-caption-margin-top)', 'lg'),
      borderRadius: vw('var(--media-caption-border-radius)', 'lg'),
    },
    '*': {
      color: 'inherit',
    },
  },
}

module.exports = { media }
