import './reset.css'
import './build.css'

import './js/fixLoadTransitions.js'
import './js/forceKeepScrollWhenResized.js'
import './js/aos.js'
import './js/parallaxImage.js'
import './js/media.js'
import './js/gallery.js'
import './js/columns.js'
